### ISSUE TITLE
The plotly.plotly module is deprecated

### ISSUE THREAD

**Issue by dmbhatti** [santosjorge/cufflinks#194]
plotly==4.0.0

```
Traceback (most recent call last):
  .
  .
  .
  File ".../lib/python3.7/site-packages/cufflinks/__init__.py", line 15, in <module>
    from . import tools
  File ".../lib/python3.7/site-packages/cufflinks/tools.py", line 6, in <module>
    import plotly.plotly as py
  File ".../lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File ".../lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.
```

**Comment by nicolaskruchten** [comment]
Fixed in #202 !

**Comment by bensdm** [comment]
do i have to git clone in order to have the bug fix or conda install should work? thanks

**Comment by danielAdama** [comment]
what worked for me:
Downgraded from the latest plotly version
pip install plotly==3.10.0
