### ISSUE TITLE
No module named 'plotly.figure_factory' while import cufflinks as cf

### ISSUE THREAD

**Issue by ahbon123** [santosjorge/cufflinks#221]
I try to import cufflinks as cf, but I get the Traceback error:

Traceback (most recent call last):

  File "<ipython-input-22-fa10b240f3e4>", line 1, in <module>
    import cufflinks as cf

  File "/usr/local/lib/python3.6/dist-packages/cufflinks/__init__.py", line 15, in <module>
    from . import tools

  File "/usr/local/lib/python3.6/dist-packages/cufflinks/tools.py", line 6, in <module>
    import plotly.figure_factory as ff

ModuleNotFoundError: No module named 'plotly.figure_factory'
Anyway, I can import from plotly.tools import FigureFactory as FF without problem.

Someone clould help? Thanks.

**Comment by eholic** [comment]
Do you use the latest cufflinks and plotly? Please let us know your environment and versions.
