### ISSUE TITLE
Tests fail with pandas>=1.0

### ISSUE THREAD

**Issue by jonringer** [santosjorge/cufflinks#236]
```
ERROR: test_bar_row_ (tests.TestIPlot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/cufflinks-0.17.3/tests.py", line 271, in test
    test_func(self, **kwargs)
  File "/build/cufflinks-0.17.3/tests.py", line 76, in bar_row_test
    self._iplot(self.df.ix[1], **kwargs)
  File "/nix/store/vf0ss77wc51c5saxghbldbjfdh6ph76q-python3.7-pandas-1.0.1/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```
located https://github.com/santosjorge/cufflinks/blob/5df644f91ad8817e85d05cec7d21cfaf9316947b/tests.py#L76

**Comment by jonringer** [comment]
closing due to staleness
