### ISSUE TITLE
Cufflink 0.17.0 Import Error

### ISSUE THREAD

**Issue by AspoSingh** [santosjorge/cufflinks#237]
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

Restarting kernel... 

 

import plotly

import cufflinks
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\colors.py", line 100, in normalize
    return normalize(cnames[color.lower()])

NameError: name 'cnames' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-f6fce55a6101>", line 1, in <module>
    import cufflinks

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\__init__.py", line 15, in <module>
    from . import tools

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\tools.py", line 13, in <module>
    from .colors import normalize, to_rgba

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\colors.py", line 749, in <module>
    reset_scales()

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\colors.py", line 646, in reset_scales
    hex_to_rgb(normalize(_)) for _ in v_]

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\colors.py", line 646, in <listcomp>
    hex_to_rgb(normalize(_)) for _ in v_]

  File "C:\ProgramData\Anaconda3\lib\site-packages\cufflinks\colors.py", line 102, in normalize
    raise CufflinksError('Not a valid color: ' + color)

CufflinksError: Not a valid color: orange

Help Please

**Comment by kodiakcrypto** [comment]
Same issue here

**Comment by esudkamp** [comment]
Actually, if you edit plotlytools.py as follows: 
```
import chart_studio.plotly as py
from import plotly.graph_objs
# from plotly.graph_objs import Figure, Layout, Bar, Box, Scatter, FigureWidget, Scatter3d, Histogram, Heatmap, Surface, Pie
```

I've gotten it to work (at least somewhat) successfully
